### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AnitaSherry** [a3ng7n/Altium-Schematic-Parser#15]
```
Traceback (most recent call last):
  File "/home/hyh/file_test/SchDoc_demo.py", line 259, in <module>
    schematic = parse(SchDoc_path, format)
  File "/home/hyh/file_test/SchDoc_demo.py", line 34, in parse
    datum[data[0].decode()] = data[1].decode('utf-8', 'ignore')
IndexError: list index out of range
```
python 3.10.13

**Comment by AnitaSherry** [comment]
![image](https://github.com/a3ng7n/Altium-Schematic-Parser/assets/96946615/32feb112-d528-4d4c-8bb8-139c323c3370)
I added the criteria for judgment
`if len(data) == 2:`
